/*
 * File: app/view/appViewport.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dalpeApp.view.appViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.appViewport',

    requires: [
        'dalpeApp.view.employesGrid',
        'dalpeApp.view.sousTraitantsGrid',
        'dalpeApp.view.clientsGrid',
        'dalpeApp.view.chantiersGrid'
    ],

    id: 'appViewport',
    layout: {
        type: 'fit'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    layout: {
                        type: 'fit'
                    },
                    title: 'Construction Julien Dalpé Inc.',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            id: 'appToolbar',
                            itemId: '',
                            items: [
                                {
                                    xtype: 'tbtext',
                                    itemId: 'userLogged',
                                    text: 'Utilisateur connecté'
                                },
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'logout',
                                    text: 'se déconnecter...'
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'tabpanel',
                            title: '',
                            activeTab: 1,
                            items: [
                                {
                                    xtype: 'panel',
                                    id: 'employesPanel',
                                    layout: {
                                        type: 'border'
                                    },
                                    title: 'Employés',
                                    items: [
                                        {
                                            xtype: 'employesGrid',
                                            flex: 1,
                                            region: 'center',
                                            split: true
                                        },
                                        {
                                            xtype: 'gridpanel',
                                            flex: 1,
                                            region: 'east',
                                            split: true,
                                            title: 'Heures',
                                            store: 'employes_hours',
                                            columns: [
                                                {
                                                    xtype: 'datecolumn',
                                                    dataIndex: 'workDate',
                                                    text: 'Date',
                                                    format: 'd-M-Y'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'hours',
                                                    text: 'Heure'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                        if (record.data.chantierId)
                                                        {
                                                            return Ext.getStore('chantiers').getById(record.data.chantierId).data.name;
                                                        }
                                                        return '';
                                                    },
                                                    dataIndex: 'chantierId',
                                                    text: 'Chantier'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    id: 'sousTraitantsPanel',
                                    layout: {
                                        type: 'border'
                                    },
                                    title: 'Sous Traitants',
                                    items: [
                                        {
                                            xtype: 'mygridpanel2',
                                            width: 561,
                                            store: 'sousTraitants',
                                            flex: 2,
                                            region: 'center',
                                            split: true
                                        },
                                        {
                                            xtype: 'panel',
                                            flex: 2,
                                            region: 'east',
                                            split: true,
                                            width: 150,
                                            layout: {
                                                type: 'fit'
                                            },
                                            items: [
                                                {
                                                    xtype: 'gridpanel',
                                                    id: 'mailsGrid',
                                                    collapsed: false,
                                                    title: 'Courriels',
                                                    store: 'mails',
                                                    selModel: Ext.create('Ext.selection.RowModel', {

                                                    }),
                                                    columns: [
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'subject',
                                                            text: 'Sujet',
                                                            flex: 1
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'chantier',
                                                            text: 'Chantier',
                                                            flex: 1
                                                        },
                                                        {
                                                            xtype: 'datecolumn',
                                                            dataIndex: 'creationDate',
                                                            text: 'Cree le'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'userCreate',
                                                            text: 'Cree par'
                                                        },
                                                        {
                                                            xtype: 'datecolumn',
                                                            dataIndex: 'sentDate',
                                                            text: 'Envoye le'
                                                        }
                                                    ],
                                                    tools: [
                                                        {
                                                            xtype: 'tool',
                                                            itemId: 'refresh',
                                                            type: 'refresh'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'clientsgrid',
                                    title: 'Clients'
                                },
                                {
                                    xtype: 'panel',
                                    id: 'chantiersPanel',
                                    layout: {
                                        type: 'border'
                                    },
                                    title: 'Chantiers',
                                    items: [
                                        {
                                            xtype: 'chantiersGrid',
                                            flex: 1,
                                            region: 'center',
                                            split: true
                                        },
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            region: 'east',
                                            split: true,
                                            width: 150,
                                            layout: {
                                                align: 'stretch',
                                                type: 'vbox'
                                            },
                                            items: [
                                                {
                                                    xtype: 'gridpanel',
                                                    flex: 1,
                                                    title: 'Hours',
                                                    store: 'chantiers_hours',
                                                    columns: [
                                                        {
                                                            xtype: 'datecolumn',
                                                            dataIndex: 'workDate',
                                                            text: 'Date'
                                                        },
                                                        {
                                                            xtype: 'numbercolumn',
                                                            dataIndex: 'hours',
                                                            text: 'Heures'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                                var employe =  Ext.getStore('employes').getById(record.data.employeId)
                                                                return (employe.data.prenom + employe.data.nom);
                                                            },
                                                            dataIndex: 'employeId',
                                                            text: 'Employe'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'gridpanel',
                                                    flex: 1,
                                                    itemId: 'documentsGrid',
                                                    title: 'Documents',
                                                    store: 'chantiers_documents',
                                                    dockedItems: [
                                                        {
                                                            xtype: 'toolbar',
                                                            dock: 'top',
                                                            items: [
                                                                {
                                                                    xtype: 'combobox',
                                                                    itemId: 'documentType',
                                                                    padding: 0,
                                                                    queryMode: 'local',
                                                                    store: 'document_type'
                                                                },
                                                                {
                                                                    xtype: 'filefield',
                                                                    itemId: 'fileUpdalod',
                                                                    padding: 0,
                                                                    width: 60,
                                                                    name: 'documentImport',
                                                                    buttonOnly: true,
                                                                    buttonText: 'Ajouter...'
                                                                }
                                                            ]
                                                        }
                                                    ],
                                                    columns: [
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'name',
                                                            text: 'Photo'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'chantierId',
                                                            text: 'ChantierId'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    id: 'logHours',
                                    title: 'Entrée des Heures',
                                    tabConfig: {
                                        xtype: 'tab',
                                        id: 'logHours_tabConfig',
                                        itemId: ''
                                    },
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            id: 'logHoursGrid',
                                            store: 'employes_logHours',
                                            columns: [
                                                {
                                                    xtype: 'datecolumn',
                                                    dataIndex: 'workDate',
                                                    text: 'WorkDate',
                                                    format: 'd-M-Y'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'hours',
                                                    text: 'Hours'
                                                }
                                            ]
                                        }
                                    ],
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    itemId: 'addHour',
                                                    text: 'Ajouter une entrée'
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'deleteHour',
                                                    text: 'Effacer l\'entreé selectionnée'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ],
                    tools: [
                        {
                            xtype: 'tool',
                            itemId: 'preferences',
                            tooltip: 'Preferences',
                            tooltipType: 'title',
                            type: 'gear'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});