/*
 * File: app/view/chantiersGrid.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dalpeApp.view.chantiersGrid', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.chantiersGrid',

    height: 250,
    id: 'chantiersGrid',
    title: 'Chantiers',
    store: 'chantiers',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            viewConfig: {

            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'name',
                    flex: 1,
                    text: 'Name'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'note',
                    flex: 1,
                    text: 'Note'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'status',
                    flex: 1,
                    text: 'Status'
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'startDate',
                    text: 'Debut',
                    format: 'd-M-Y'
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'endDate',
                    text: 'Fin',
                    format: 'd-M-Y'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'clientName',
                    flex: 1,
                    text: 'Client'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'add',
                            text: 'Creer un nouveau chantier'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});