/*
 * File: app/view/editSousTraitant.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dalpeApp.view.editSousTraitant', {
    extend: 'Ext.window.Window',
    alias: 'widget.editSousTraitant',

    height: 541,
    minHeight: 540,
    minWidth: 650,
    width: 650,
    layout: {
        align: 'stretch',
        type: 'vbox'
    },
    title: 'Edit Sous Traitant',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    flex: 1,
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'panel',
                            flex: 1,
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'panel',
                                    flex: 1,
                                    margins: 10,
                                    border: 0,
                                    layout: {
                                        align: 'stretch',
                                        type: 'vbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            maxHeight: 25,
                                            fieldLabel: 'Compagnie'
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            maxHeight: 25,
                                            fieldLabel: 'Contact'
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            maxHeight: 25,
                                            fieldLabel: 'Telephone'
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            maxHeight: 25,
                                            fieldLabel: 'Fax'
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            maxHeight: 25,
                                            fieldLabel: 'Couriel'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    flex: 1,
                                    margins: 10,
                                    border: 0,
                                    autoScroll: false,
                                    layout: {
                                        align: 'stretch',
                                        type: 'vbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            maxHeight: 25,
                                            fieldLabel: 'Adresse'
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            maxHeight: 25,
                                            fieldLabel: 'Label'
                                        },
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            border: 0,
                                            layout: {
                                                align: 'stretch',
                                                type: 'hbox'
                                            },
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    maxHeight: 25,
                                                    fieldLabel: 'Code Postal',
                                                    labelWidth: 75
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    maxHeight: 25,
                                                    fieldLabel: 'Ville',
                                                    labelAlign: 'right',
                                                    labelWidth: 30
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'filefield',
                                            flex: 1,
                                            fieldLabel: 'Import Document'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            layout: {
                                type: 'fit'
                            },
                            title: 'Note',
                            items: [
                                {
                                    xtype: 'textfield'
                                }
                            ]
                        },
                        {
                            xtype: 'gridpanel',
                            flex: 1,
                            title: 'Documents Importes',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    text: 'String'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    dataIndex: 'number',
                                    text: 'Number'
                                },
                                {
                                    xtype: 'datecolumn',
                                    dataIndex: 'date',
                                    text: 'Date'
                                },
                                {
                                    xtype: 'booleancolumn',
                                    dataIndex: 'bool',
                                    text: 'Boolean'
                                }
                            ],
                            viewConfig: {

                            }
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    flex: 1,
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'tbspacer',
                            height: 10,
                            width: 507
                        },
                        {
                            xtype: 'button',
                            text: 'Enregistrer'
                        },
                        {
                            xtype: 'button',
                            text: 'Annuler'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});