/*
 * File: app/view/editChantierWindow.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dalpeApp.view.editChantierWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.editChantierWindow',

    height: 302,
    id: 'editChantierWindow',
    minHeight: 290,
    minWidth: 650,
    width: 839,
    layout: {
        align: 'stretch',
        type: 'vbox'
    },
    title: 'Edit Chantier',
    constrain: true,
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    flex: 1,
                    frame: false,
                    itemId: 'editForm',
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'panel',
                            flex: 1,
                            border: 0,
                            margin: 5,
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'panel',
                                    flex: 1,
                                    margins: '10',
                                    border: 0,
                                    layout: {
                                        align: 'stretch',
                                        type: 'vbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            maxHeight: 25,
                                            name: 'name',
                                            fieldLabel: 'Nom',
                                            allowBlank: false,
                                            blankText: 'Ce champ est requis'
                                        },
                                        {
                                            xtype: 'textareafield',
                                            flex: 1,
                                            name: 'note',
                                            fieldLabel: 'Notes'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    flex: 1,
                                    margins: '10',
                                    border: 0,
                                    autoScroll: false,
                                    layout: {
                                        align: 'stretch',
                                        type: 'vbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            flex: 1,
                                            name: 'clientId',
                                            fieldLabel: 'Client',
                                            labelWidth: 150,
                                            allowBlank: false,
                                            displayField: 'displayName',
                                            queryMode: 'local',
                                            store: 'clients',
                                            valueField: 'id'
                                        },
                                        {
                                            xtype: 'combobox',
                                            flex: 1,
                                            name: 'status',
                                            fieldLabel: 'Status',
                                            labelWidth: 150,
                                            allowBlank: false,
                                            store: [
                                                'Devis',
                                                'Encours',
                                                'Termine'
                                            ]
                                        },
                                        {
                                            xtype: 'datefield',
                                            flex: 1,
                                            name: 'startDate',
                                            fieldLabel: 'Debut des Travaux',
                                            labelWidth: 150,
                                            submitFormat: 'Y-m-d'
                                        },
                                        {
                                            xtype: 'datefield',
                                            flex: 1,
                                            name: 'endDate',
                                            fieldLabel: 'Fin des Travaux',
                                            labelWidth: 150,
                                            submitFormat: 'Y-m-d'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'numberfield',
                            flex: 1,
                            hidden: true,
                            name: 'id',
                            fieldLabel: 'Label'
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    flex: 1,
                    dock: 'bottom',
                    itemId: 'toolBar',
                    items: [
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            itemId: 'enregistrer',
                            text: 'Enregistrer'
                        },
                        {
                            xtype: 'button',
                            itemId: 'annuler',
                            text: 'Annuler'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});