/*
 * File: app/view/editSousTraitantWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dalpeApp.view.editSousTraitantWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.editSousTraitantWindow',

    height: 482,
    id: 'editSousTraitantWindow',
    minWidth: 1300,
    width: 1300,
    constrain: true,
    layout: {
        align: 'stretch',
        type: 'hbox'
    },
    title: 'Edit Sous Traitant',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    flex: 1,
                    border: 0,
                    itemId: 'editForm',
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'panel',
                            flex: 1,
                            border: 0,
                            margin: 5,
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'panel',
                                    flex: 1,
                                    margins: '10',
                                    border: 0,
                                    layout: {
                                        align: 'stretch',
                                        type: 'vbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            maxHeight: 25,
                                            fieldLabel: 'Compagnie',
                                            name: 'name',
                                            allowBlank: false,
                                            blankText: 'Ce champ est requis'
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            maxHeight: 25,
                                            fieldLabel: 'Contact',
                                            name: 'contactName'
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            maxHeight: 25,
                                            fieldLabel: 'Telephone',
                                            name: 'phone'
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            maxHeight: 25,
                                            fieldLabel: 'Cellulaire',
                                            name: 'cell'
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            maxHeight: 25,
                                            fieldLabel: 'Fax',
                                            name: 'fax'
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            maxHeight: 25,
                                            fieldLabel: 'Couriel',
                                            name: 'mail',
                                            inputType: 'email',
                                            vtype: 'email'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    flex: 1,
                                    margins: '10',
                                    border: 0,
                                    layout: {
                                        align: 'stretch',
                                        type: 'vbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            maxHeight: 25,
                                            fieldLabel: 'Adresse',
                                            name: 'adresse'
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            maxHeight: 25,
                                            fieldLabel: 'Code Postal',
                                            name: 'codePostal'
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            maxHeight: 25,
                                            fieldLabel: 'Ville',
                                            name: 'ville'
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            maxHeight: 25,
                                            fieldLabel: 'Province',
                                            name: 'province'
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            maxHeight: 25,
                                            fieldLabel: 'Site Internet',
                                            name: 'siteWeb'
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            maxHeight: 25,
                                            fieldLabel: 'License RBQ',
                                            name: 'licenseRbq'
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            maxHeight: 25,
                                            fieldLabel: 'Tps',
                                            name: 'tps'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            border: 0,
                            height: 150,
                            margin: 5,
                            maxHeight: 150,
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    flex: 1.5,
                                    itemId: 'specialitesGrid',
                                    width: 149,
                                    hideHeaders: true,
                                    store: 'specialiteLinkSousTraitant',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'name',
                                            text: 'String',
                                            flex: 7
                                        },
                                        {
                                            xtype: 'actioncolumn',
                                            flex: 1,
                                            items: [
                                                {
                                                    handler: function(view, rowIndex, colIndex, item, e) {
                                                        var mySpecialite = view.store.data.items[rowIndex].data;

                                                        var mySousTraitant = Ext.getCmp('editSousTraitantWindow').down('form').getValues();

                                                        SousTraitants.removeLinkWithSpecialite(mySpecialite, mySousTraitant);


                                                        Ext.getCmp('editSousTraitantWindow').down('#specialitesGrid').store.load();
                                                    },
                                                    icon: 'images/delete.png',
                                                    tooltip: 'Enlever la specialite'
                                                }
                                            ]
                                        }
                                    ],
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    handler: function(button, event) {
                                                        //On eut etre sur que le sous traitant est cree avant d'ajouter une specialite
                                                        var myForm = button.up('window').down('form');
                                                        if (myForm.getValues().id)
                                                        {
                                                            //Lorsqu'on click, on veut ouvrir une fenetre avec un combobox listant les specialites
                                                            var addSpecialiteWindow = Ext.widget('windowAddSpecialite').show();
                                                            var specialiteStore = addSpecialiteWindow.down('#comboSpecialites').store;
                                                            specialiteStore.clearFilter();
                                                            specialiteStore.load();
                                                        }
                                                        else
                                                        {
                                                            Ext.MessageBox.alert('Attention','Vous devez d\'abord cree le soustraitant');
                                                        }

                                                    },
                                                    text: 'Ajouter une specialite'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    flex: 3,
                                    border: 0,
                                    padding: '0 0 0 30',
                                    width: 100,
                                    layout: {
                                        type: 'fit'
                                    },
                                    items: [
                                        {
                                            xtype: 'textareafield',
                                            border: 0,
                                            width: 341,
                                            fieldLabel: 'Note',
                                            labelWidth: 40,
                                            name: 'note'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'numberfield',
                            flex: 1,
                            hidden: true,
                            fieldLabel: 'Label',
                            name: 'id'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    border: 0,
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    items: [
                        {
                            xtype: 'form',
                            flex: 1,
                            border: 0,
                            height: 230,
                            itemId: 'fileForm',
                            maxHeight: 230,
                            minHeight: 230,
                            width: 618,
                            layout: {
                                align: 'stretch',
                                defaultMargins: {
                                    top: 10,
                                    right: 10,
                                    bottom: 0,
                                    left: 20
                                },
                                type: 'vbox'
                            },
                            items: [
                                {
                                    xtype: 'filefield',
                                    flex: 1,
                                    maxHeight: 30,
                                    fieldLabel: 'Document',
                                    name: 'documentImport',
                                    allowBlank: false,
                                    buttonMargin: 15,
                                    buttonText: 'Rechercher...'
                                },
                                {
                                    xtype: 'combobox',
                                    flex: 1,
                                    maxHeight: 30,
                                    maxWidth: 250,
                                    fieldLabel: 'Type',
                                    name: 'documentTypeId',
                                    allowBlank: false,
                                    emptyText: 'type de document...',
                                    displayField: 'name',
                                    store: 'document_type',
                                    valueField: 'id'
                                },
                                {
                                    xtype: 'textareafield',
                                    flex: 1,
                                    height: 60,
                                    maxHeight: 60,
                                    minHeight: 60,
                                    fieldLabel: 'Note',
                                    name: 'documentNote'
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    layout: {
                                        align: 'stretch',
                                        type: 'hbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            itemId: 'saveDocument',
                                            maxHeight: 30,
                                            maxWidth: 150,
                                            minWidth: 150,
                                            width: 150,
                                            text: 'Importer le document'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'gridpanel',
                            flex: 1,
                            margins: '5',
                            height: 150,
                            maxHeight: 150,
                            title: 'Documents Importes',
                            store: 'documents',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                        return '<a href="'+record.data.path+'" target="_blank">'+value+'</a>';
                                    },
                                    dataIndex: 'name',
                                    text: 'Nom',
                                    flex: 1
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'note',
                                    text: 'Note'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                        var document_type_Store = Ext.getStore('document_type');
                                        return document_type_Store.getById(value).data.name;

                                    },
                                    dataIndex: 'type',
                                    text: 'Type'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'creationDate',
                                    text: 'Date de création'
                                }
                            ]
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    flex: 1,
                    dock: 'bottom',
                    itemId: 'toolBar',
                    items: [
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            itemId: 'enregistrer',
                            text: 'Enregistrer'
                        },
                        {
                            xtype: 'button',
                            itemId: 'annuler',
                            text: 'Fermer'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});