/*
 * File: app/view/loginWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dalpeApp.view.loginWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.loginWindow',

    autoShow: true,
    draggable: false,
    height: 280,
    id: 'loginWindow',
    width: 302,
    resizable: false,
    layout: {
        type: 'fit'
    },
    bodyBorder: false,
    closable: false,
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    title: 'Construction Julien Dalpé',
                    items: [
                        {
                            xtype: 'form',
                            itemId: 'loginForm',
                            bodyPadding: 10,
                            title: 'Identification',
                            items: [
                                {
                                    xtype: 'textfield',
                                    maxHeight: 25,
                                    fieldLabel: 'Nom d\'utilisateur',
                                    name: 'userName',
                                    allowBlank: false,
                                    blankText: 'Ce champ est requis'
                                },
                                {
                                    xtype: 'textfield',
                                    itemId: 'password',
                                    maxHeight: 25,
                                    fieldLabel: 'Mot de passe',
                                    name: 'passWord',
                                    inputType: 'password',
                                    allowBlank: false,
                                    blankText: 'Ce champ est requis'
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'bottom',
                                    items: [
                                        {
                                            xtype: 'tbfill'
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'login',
                                            text: 'Se connecter...'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'image',
                            maxWidth: 280,
                            minWidth: 280,
                            width: 280,
                            src: 'images/dalpe.jpg'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});