/*
 * File: app/view/mailsGrid.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dalpeApp.view.mailsGrid', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.mailsgrid',

    height: 414,
    id: 'mailsGrid',
    width: 683,
    collapsed: false,
    title: 'Courriels',
    store: 'mails',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            selModel: Ext.create('Ext.selection.RowModel', {

            }),
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'subject',
                    text: 'Sujet'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'chantier',
                    text: 'Chantier'
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'creationDate',
                    text: 'Cree le'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'userCreate',
                    text: 'Cree par'
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'sentDate',
                    text: 'Envoye le'
                }
            ]
        });

        me.callParent(arguments);
    }

});