/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dalpeApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'dalpeApp.view.employesGrid',
        'dalpeApp.view.sousTraitantsGrid',
        'dalpeApp.view.clientsGrid',
        'dalpeApp.view.chantiersGrid'
    ],

    id: 'mainView',
    layout: {
        type: 'fit'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    title: 'Construction Julien Dalpe Inc.',
                    activeTab: 1,
                    items: [
                        {
                            xtype: 'panel',
                            title: 'Employe',
                            items: [
                                {
                                    xtype: 'employesGrid'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            layout: {
                                type: 'border'
                            },
                            title: 'Sous Traitants',
                            items: [
                                {
                                    xtype: 'mygridpanel2',
                                    width: 561,
                                    store: 'sousTraitants',
                                    flex: 2,
                                    region: 'center',
                                    split: true
                                },
                                {
                                    xtype: 'panel',
                                    flex: 2,
                                    region: 'east',
                                    split: true,
                                    width: 150,
                                    layout: {
                                        type: 'accordion'
                                    },
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            id: 'mailsGrid',
                                            width: 150,
                                            collapsed: false,
                                            collapsible: true,
                                            title: 'Courriels',
                                            store: 'mails',
                                            viewConfig: {

                                            },
                                            selModel: Ext.create('Ext.selection.RowModel', {

                                            }),
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'subject',
                                                    text: 'Sujet'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                        var chantiersStore = Ext.getStore('chantiers');
                                                        var chantierId = record.data.chantierId;
                                                        if (chantierId)
                                                        {

                                                            return chantiersStore.getById(chantierId).data.name;
                                                        }
                                                        else
                                                        {
                                                            return '';
                                                        }
                                                    },
                                                    dataIndex: 'chantierId',
                                                    text: 'Chantier'
                                                },
                                                {
                                                    xtype: 'datecolumn',
                                                    dataIndex: 'creationDate',
                                                    text: 'Cree le'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                        var employesStore = Ext.getStore('employes');
                                                        var userId = record.data.userCreateId;
                                                        if (userId)
                                                        {

                                                            return employesStore.getById(userId).data.prenom + " " + employesStore.getById(userId).data.nom;
                                                        }
                                                        else
                                                        {
                                                            return '';
                                                        }
                                                    },
                                                    dataIndex: 'userCreateId',
                                                    text: 'Cree par'
                                                },
                                                {
                                                    xtype: 'datecolumn',
                                                    dataIndex: 'sentDate',
                                                    text: 'Envoye le'
                                                }
                                            ],
                                            listeners: {
                                                itemdblclick: {
                                                    fn: me.onMailsGridItemDblClick,
                                                    scope: me
                                                }
                                            },
                                            tools: [
                                                {
                                                    xtype: 'tool',
                                                    itemId: 'refresh',
                                                    type: 'refresh'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'gridpanel',
                                            id: 'documentsGrid',
                                            width: 150,
                                            collapsed: true,
                                            title: 'Documents',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'String'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'number',
                                                    text: 'Number'
                                                },
                                                {
                                                    xtype: 'datecolumn',
                                                    dataIndex: 'date',
                                                    text: 'Date'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Boolean'
                                                }
                                            ],
                                            viewConfig: {

                                            },
                                            dockedItems: [
                                                {
                                                    xtype: 'toolbar',
                                                    dock: 'top',
                                                    items: [
                                                        {
                                                            xtype: 'filefield',
                                                            id: 'documentUpload',
                                                            fieldLabel: 'Label'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'clientsgrid',
                            title: 'Clients'
                        },
                        {
                            xtype: 'chantiersGrid'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onMailsGridItemDblClick: function(tablepanel, record, item, index, e, options) {


        var myMail = record.data;



        //On reload le store de liens
        var linkStore = Ext.getStore('mailLinkSousTraitant');
        linkStore.proxy.extraParams = {mailId:myMail.id};
        linkStore.load();

        //On affiche la fenetre
        var mailWindow = Ext.widget('mailWindow');
        //On update le form
        var myForm = mailWindow.down('form');
        myForm.getForm().setValues(myMail);


        if (myMail.sentDate)
        {
            //Le form va etre read Only
            //Ext.Msg.alert('Attention', 'Ce mail a deja ete envoye, vous ne pourrez donc pas le modifier.');
            mailWindow.down('#comboChantiers').readOnly = true;
            mailWindow.down('#subject').setReadOnly(true);
            mailWindow.down('#message').setReadOnly(true);


        }

    }

});