/*
 * File: app/view/Viewport.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dalpeApp.view.Viewport', {
    extend: 'dalpeApp.view.appViewport',
    renderTo: Ext.getBody(),
    requires: [
        'dalpeApp.view.mailsGrid',
        'dalpeApp.view.appViewport',
        'dalpeApp.view.mailWindow',
        'dalpeApp.view.sousTraitantsContextMenu',
        'dalpeApp.view.editSousTraitantWindow',
        'dalpeApp.view.editEmployeWindow',
        'dalpeApp.view.editClientWindow',
        'dalpeApp.view.editChantierWindow',
        'dalpeApp.view.windowAddSpecialite',
        'dalpeApp.view.employesHoursGrid',
        'dalpeApp.view.loginWindow',
        'dalpeApp.view.editEmployeHour'
    ]
});