/*
 * File: app/model/colonne.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dalpeApp.model.colonne', {
    extend: 'Ext.data.Model',

    fields: [
        {
            mapping: 'Field',
            name: 'name',
            type: 'auto'
        },
        {
            mapping: 'Type',
            name: 'type'
        },
        {
            name: 'foreignTable'
        },
        {
            mapping: 'Null',
            name: 'allowNull'
        },
        {
            mapping: 'Default',
            name: 'DefaultValue'
        }
    ]
});