/*
 * File: app/model/mail.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dalpeApp.model.mail', {
    extend: 'Ext.data.Model',

    idProperty: 'id',

    fields: [
        {
            name: 'id',
            type: 'int'
        },
        {
            name: 'message',
            type: 'string'
        },
        {
            name: 'creationDate',
            dateFormat: 'c',
            type: 'date'
        },
        {
            name: 'subject'
        },
        {
            name: 'chantierId',
            type: 'int',
            useNull: true
        },
        {
            name: 'userCreateId',
            type: 'int'
        },
        {
            name: 'sentDate',
            dateFormat: 'c',
            type: 'date'
        }
    ]
});