/*
 * File: app/model/specialite.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dalpeApp.model.specialite', {
    extend: 'Ext.data.Model',

    fields: [
        {
            mapping: '_id',
            name: 'id',
            type: 'string'
        },
        {
            name: 'name'
        }
    ],

    proxy: {
        type: 'rest',
        url: 'api/specialites',
        reader: {
            type: 'json'
        },
        writer: {
            type: 'json',
            writeRecordId: false
        }
    }
});