/*
 * File: app/controller/clients.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dalpeApp.controller.clients', {
    extend: 'Ext.app.Controller',

    models: [
        'client'
    ],
    stores: [
        'clients'
    ],
    views: [
        'editClientWindow'
    ],

    refs: [
        {
            ref: 'clientsGrid',
            selector: '#clientsGrid'
        }
    ],

    onAddClick: function(button, e, eOpts) {
        Ext.widget('editClientWindow').show();
    },

    onEnregistrerClick: function(button, e, eOpts) {
        //On va chercher les infos du form
        var myForm = Ext.getCmp('editClientWindow').down('form').getForm();
        if (! myForm.isValid())
        {
            return
        }

        var clientData = myForm.getValues();
        if (clientData.id)
        {
            //On update la DB et on ferme la window
            Clients.update(clientData, function(){
                //On peut maintenant fermer la window
                button.up('window').close();
                this.getClientsGrid().store.load();
            },this);
        }
        else
        {
            //On cree le nouvel employe
            //On update la DB et on ferme la window
            Clients.create(clientData, function(newRecord){
                //On peut maintenant fermer la window
                button.up('window').close();
                //On rajoute le nouvel employe dans le store
                this.getClientsGrid().store.load();
            },this);

        }
    },

    onClientsGridItemDblClick: function(dataview, record, item, index, e, eOpts) {

        //On affiche la fenetre d'edit
        var editClientWindow = Ext.widget('editClientWindow');

        //On load le soustraitant selecitonne dans le form
        var myForm = editClientWindow.down('form');

        //On prend le record selectionne
        var selectedRecord = this.getClientsGrid().selModel.getSelection()[0];
        //On retourne chercher le data dans la db, au cas ou un autre user ait modifie la fiche
        Clients.get(selectedRecord.data, function(recordFromDb){
            var myData = recordFromDb[0];
            var myClient = this.getClientModel().create(myData);
            myForm.getForm().loadRecord(myClient);
        }, this)




        editClientWindow.show();

    },

    onClientsGridActivate: function(component, eOpts) {
        this.getClientsStore().load();
    },

    init: function(application) {
        this.control({
            "#clientsGrid #add": {
                click: this.onAddClick
            },
            "#editClientWindow #enregistrer": {
                click: this.onEnregistrerClick
            },
            "#clientsGrid": {
                itemdblclick: this.onClientsGridItemDblClick,
                activate: this.onClientsGridActivate
            }
        });
    }

});
