/*
 * File: app/controller/employes.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dalpeApp.controller.employes', {
    extend: 'Ext.app.Controller',

    models: [
        'employe'
    ],
    stores: [
        'employes'
    ],
    views: [
        'editEmployeWindow'
    ],

    refs: [
        {
            ref: 'employesGrid',
            selector: '#employesGrid'
        }
    ],

    onAddEmployeClick: function(button, e, eOpts) {
        Ext.widget('editEmployeWindow').show();
    },

    onEmployesGridSelect: function(rowmodel, record, index, eOpts) {
        var hours_store = Ext.getStore('employes_hours');
        hours_store.proxy.extraParams ={employeId:record.data.id};
        hours_store.load();
    },

    onEmployesPanelActivate: function(component, eOpts) {
        this.getEmployesStore().load();

    },

    onEditEmployeClick: function(button, e, eOpts) {
        //On prend le record selectionne
        var selectedRecord = this.getEmployesGrid().selModel.getSelection()[0];
        if (!selectedRecord) {
            Ext.Msg.alert('Attention','Vous devez selectionner un employe...').setWidth(200);
            return;
        }

        //On affiche la fenetre d'edit
        var editEmployeWindow = Ext.widget('editEmployeWindow');

        //On load le soustraitant selecitonne dans le form
        var myForm = editEmployeWindow.down('form');

        //On retourne chercher le data dans la db, au cas ou un autre user ait modifie la fiche
        Employes.get(selectedRecord.data, function(recordFromDb){
            var myData = recordFromDb[0];
            var myEmploye = this.getEmployeModel().create(myData);
            myForm.getForm().loadRecord(myEmploye);
            myForm.down('#photo').setSrc(myEmploye.data.photo);
        }, this);

        editEmployeWindow.show();

    },

    onSavePhotoClick: function(button, e, eOpts) {
        var myEditForm = button.up('window').down('#editForm').getForm();
        var employeId = myEditForm.getValues().id;

        if (! employeId) {
            Ext.Msg.alert('Attention','Vous devez d\'abord créer l\'employer avant de rajouter une photo');
        }
        else {

            var form = button.up('#fileForm').getForm();
            if(form.isValid()){
                form.submit({
                    url: 'employe_photo_upload.php',
                    scope:this,
                    params: {
                        employeId: employeId
                    },
                    waitMsg: 'Sauvegarde de la photo...',
                    success: function(fp, o) {

                    }
                });
            }
        }
    },

    onAnnulerClick: function(button, e, eOpts) {
        button.up('window').close();
    },

    onEnregistrerClick: function(button, e, eOpts) {
        //On va chercher les infos du form
        var myForm = Ext.getCmp('editEmployeWindow').down('form').getForm();
        if (! myForm.isValid()) {
            return;
        }

        var employeData = myForm.getValues();
        if (employeData.id) {
            //On update la DB et on ferme la window
            Employes.update(employeData, function(){
                //On peut maintenant fermer la window
                button.up('window').close();
                this.getEmployesGrid().store.load();
            },this);
        }
        else {
            //On cree le nouvel employe
            //On update la DB et on ferme la window
            Employes.create(employeData, function(newRecord){
                //On peut maintenant fermer la window
                button.up('window').close();
                //On rajoute le nouvel employe dans le store
                this.getEmployesGrid().store.load();
            },this);

        }
    },

    init: function(application) {
        this.control({
            "#employesGrid #addEmploye": {
                click: this.onAddEmployeClick
            },
            "#employesGrid": {
                select: this.onEmployesGridSelect
            },
            "#employesPanel": {
                activate: this.onEmployesPanelActivate
            },
            "#editEmploye": {
                click: this.onEditEmployeClick
            },
            "editEmployeWindow #savePhoto": {
                click: this.onSavePhotoClick
            },
            "editEmployeWindow #annuler": {
                click: this.onAnnulerClick
            },
            "editEmployeWindow #enregistrer": {
                click: this.onEnregistrerClick
            }
        });
    }

});
