/*
 * File: app/controller/global.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dalpeApp.controller.global', {
    extend: 'Ext.app.Controller',

    onViewportAfterRender: function(component, eOpts) {
        Employes.checkLoginSession(function(response){
            if (response) {
                user_logged = response[0].id;
                var myAppToolbar = Ext.getCmp('appToolbar');
                myAppToolbar.down('#userLogged').setText('Utilisateur connecté: ' + response[0].prenom + " " + response[0].nom);
            }
            else {
                //Ext.widget('loginWindow');
            }
        }, this);
    },

    onLogoutButtonClick: function(button, e, eOpts) {
        Employes.logout(function(){
            Ext.widget('loginWindow');
        }, this);
    },

    init: function(application) {
        this.control({
            "#appViewport": {
                afterrender: this.onViewportAfterRender
            },
            "#appViewport #logout": {
                click: this.onLogoutButtonClick
            }
        });
    }

});
