/*
 * File: app/controller/loginViewPort.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dalpeApp.controller.loginViewPort', {
    extend: 'Ext.app.Controller',

    onLoginClick: function(button, e, options) {
        var myForm = button.up('panel').down('form').getForm();
        if (!myForm.isValid())
        {return;}

        //On verifie l'identification dans la base de donnees...

        var formValues = myForm.getValues();
        myForm.reset();
        Employes.login(formValues, this.verifyInfos);
    },

    verifyInfos: function(response) {

        if (response.length)
        {
            //L'authentification a fonctionne, on peut rentrer dans l'application
            var appViewport = Ext.getCmp('appViewport');
            appViewport.setUI();
            var myAppToolbar = Ext.getCmp('appToolbar');
            myAppToolbar.down('#userLogged').setText('Utilisateur connecté: ' + response[0].prenom + " " + response[0].nom);
        }
        else
        {
            Ext.Msg.alert('Attention', 'Nom d\'utilisateur ou mot de passe incorrects.');
        }
    },

    init: function(application) {
        this.control({
            "#loginViewport #login": {
                click: this.onLoginClick
            }
        });
    }

});
