/*
 * File: app/controller/mails_grid.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('dalpeApp.controller.mails_grid', {
    extend: 'Ext.app.Controller',

    stores: [
        'chantiers',
        'mailLinkSousTraitant'
    ],

    onMailsGridItemDblClick: function(dataview, record, item, index, e, eOpts) {
        //On reload le store des chantiers, puis on show la window

        this.getChantiersStore().load({
            scope:this,
            callback:function(){
                this.showMailWindow(record);
            }
        })


    },

    showMailWindow: function(record) {
        var myMail = record.data;



        //On reload le store de liens
        var linkStore = this.getMailLinkSousTraitantStore();
        linkStore.proxy.extraParams = {mailId:myMail.id};
        linkStore.load();

        //On affiche la fenetre
        var mailWindow = Ext.widget('mailWindow');
        //On update le form
        var myForm = mailWindow.down('form');
        myForm.getForm().setValues(myMail);


        if (myMail.sentDate)
        {
            //Le form va etre read Only
            //Ext.Msg.alert('Attention', 'Ce mail a deja ete envoye, vous ne pourrez donc pas le modifier.');
            mailWindow.down('#comboChantiers').readOnly = true;
            mailWindow.down('#subject').setReadOnly(true);
            mailWindow.down('#message').setReadOnly(true);

            //On hide les boutons send et save
            mailWindow.down('#save').hide();
            mailWindow.down('#send').hide();
            //On hide  les boutons add et remove destinataire
            mailWindow.down('#add').hide();
            mailWindow.down('#remove').hide();

        }

    },

    init: function(application) {
        this.control({
            "#mailsGrid": {
                itemdblclick: this.onMailsGridItemDblClick
            }
        });
    }

});
