<?php
require_once('FirePHPCore/fb.php');
fb('firephp is ON');



$API = array(
    
    'Employes'=>array(
        'methods'=>array(
            'get'=>array(
                'len'=>1
            ),
            'get_hours'=>array(
                'len'=>1
            ),
            'update_hour'=>array(
                'len'=>1
            ),
            'log_hour'=>array(
                'len'=>1
            ),
            'delete_hour'=>array(
                'len'=>1
            ),
            'login'=>array(
                'len'=>1
            ),
            'checkLoginSession'=>array(
                'len'=>0
            ),
            'logout'=>array(
                'len'=>0
            ),
            'update'=>array(
                'len'=>1
            ),
            'delete'=>array(
                'len'=>1
            ),
            'create'=>array(
                'len'=>1
            )
        )
    ),
	'Chantiers'=>array(
        'methods'=>array(
            'get'=>array(
                'len'=>1
            ),
            'get_documents'=>array(
                'len'=>1
            ),
            'update'=>array(
                'len'=>1
            ),
            'delete'=>array(
                'len'=>1
            ),
            'create'=>array(
                'len'=>1
            )
        )
    ),
	'Clients'=>array(
        'methods'=>array(
            'get'=>array(
                'len'=>1
            ),
            'update'=>array(
                'len'=>1
            ),
            'delete'=>array(
                'len'=>1
            ),
            'create'=>array(
                'len'=>1
            )
        )
    ),
	'Documents'=>array(
        'methods'=>array(
            'get'=>array(
                'len'=>1
            ),
            'get_type'=>array(
                'len'=>1
            )
        )
    ),
	'SousTraitants'=>array(
        'methods'=>array(
            'get'=>array(
                'len'=>1
            ),
            'getSpecialites'=>array(
                'len'=>1
            ),
            'setLinkWithSpecialite'=>array(
                'len'=>2
            ),
            'removeLinkWithSpecialite'=>array(
                'len'=>2
            ),
            'update'=>array(
                'len'=>1
            ),
            'delete'=>array(
                'len'=>1
            ),
            'create'=>array(
                'len'=>1
            ),
            'sendMail'=>array(
                'len'=>1
            )
            
        )
    ),
	'Mails'=>array(
		'methods'=>array(
			'create'=>array(
				'len'=>1
			),
			'get'=>array(
				'len'=>1
			),
			'getMailFromSousTraitant'=>array(
				'len'=>1
			),
			'send'=>array(
				'len'=>2
			),
			'update'=>array(
				'len'=>1
			),
			'saveLinkSoustraitant'=>array(
				'len'=>2
			),
			'getLinkSoustraitant'=>array(
				'len'=>1
			),'removeLinkSousTraitant'=>array(
				'len'=>2
			)
		)
	)
    
);